name:                haskell-to-elm
version:             0.3.2.0
github:              "folq/haskell-to-elm"
license:             BSD3
author:              "Olle Fredriksson"
maintainer:          "fredriksson.olle@gmail.com"
copyright:           "2019 Olle Fredriksson"
tested-with:         GHC == 8.4.3, GHC == 8.6.5, GHC == 8.8.3, GHC == 9.2.5

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Generate Elm types and JSON encoders and decoders from Haskell types
category:            Elm, Compiler, Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/folq/haskell-to-elm#readme>

dependencies:
- aeson >= 1.4.0
- base >= 4.7 && < 5
- bound >= 2.0.0
- elm-syntax >= 0.3.0 && < 0.3.4
- generics-sop >= 0.4.0 && < 0.6.0
- text >= 1.2.0
- time >= 1.8.0
- unordered-containers >= 0.2.8
- vector >= 0.12

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -funbox-strict-fields

library:
  source-dirs: src
  other-modules: Language.Haskell.To.Elm.DataShape

tests:
  haskell-to-elm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-to-elm

flags:
  examples:
    description: Build examples
    manual: true
    default: false

executables:
  user-example:
    source-dirs: examples
    main: User.hs
    dependencies:
      - haskell-to-elm
    when:
      condition: "!flag(examples)"
      buildable: false

  parameterised-example:
    source-dirs: examples
    main: Parameterised.hs
    dependencies:
      - haskell-to-elm
    when:
      condition: "!flag(examples)"
      buildable: false

  deriving-via-example:
    source-dirs: examples
    main: DerivingVia.hs
    dependencies:
      - haskell-to-elm
    when:
      condition: "!flag(examples)"
      buildable: false
